from typing import Optional
from pydantic import BaseModel
from enum import Enum


class DesiredRuntimeCapability(str, Enum):
    AUTHENTICATION = "authentication"


class App(BaseModel):
    """
    The top-level schema representing an application, containing metadata and a collection of surface ids.
    """

    version: int = 1
    """The version of the application schema. Currently always 1."""

    id: str
    """A unique identifier for the application."""
    name: Optional[str]
    """The name of the application."""
    description: Optional[str] = ""
    """A brief description of the application."""

    icon: Optional[str] = None
    """An optional icon URL representing the application, available for clients that can remember used applications."""

    rootUrl: Optional[str] = None
    """The root URL of the provider, from which FATS URLs will be generated (i.e. URL/surface/{surfaceId}). Will be auto-generated by the FATS runtime if not specified."""

    surfaceIds: list[str]
    """A list of unique identifiers for the surfaces that make up the application."""

    desiredRuntimeCapabilities: Optional[list[DesiredRuntimeCapability]] = None
    """A list of desired runtime capabilities that the application would like to utilize, such as user authentication from the runtime environment."""
